name: Setup Python venv
description: Setup Python virtual environment with caching for uv-managed dependencies

inputs:
  python-version:
    description: Python version to use
    required: false
    default: '3.12'

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v7
      id: setup-python
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v10.0.0
      with:
        version: '0.12.4'
        # we just cache the venv-dir directly in action-setup-venv
        enable-cache: false

    - name: Restore venv cache
      uses: actions/cache@v6
      id: cache-venv
      with:
        path: .venv
        key: setup-venv-${{ runner.os }}-${{ runner.arch }}-py-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('uv.lock') }}-uv-sync-frozen-all

    - name: Create venv
      if: steps.cache-venv.outputs.cache-hit != 'true'
      run: python -m venv .venv
      shell: bash

    - name: Activate venv
      run:
        | # zizmor: ignore[github-env] VIRTUAL_ENV is a local venv path, not attacker-controlled
        source .venv/bin/activate
        echo "VIRTUAL_ENV=${VIRTUAL_ENV}" >> "${GITHUB_ENV}"
        echo "${VIRTUAL_ENV}/bin" >> "${GITHUB_PATH}"
      shell: bash

    - name: Install dependencies
      run: uv sync --frozen --active --all-groups --all-extras
      shell: bash
